package econet

var PortMap = map[byte]string{
	0x00: "Immediate Operation",
	0x4D: "MUGINS",
	0x54: "Digital Services Tape Store",
	0x90: "FileServer Reply",
	0x91: "FileServer data",
	0x93: "Remote",
	0x99: "FileServer Command",
	0x9C: "Bridge",
	0x9D: "Resource Locator",
	0x9E: "Printer Server Enquiry Reply",
	0x9F: "Printer Server Enquiry",
	0xA0: "SJ Research *FAST protocol",
	0xAF: "SJ Research Nexus net find reply port - SJVirtualEconet",
	0xB0: "Find Server",
	0xB1: "Find Server Reply",
	0xB2: "Teletext Server Command",
	0xB3: "Teletext Server Page",
	0xB4: "Teletext",
	0xB5: "Teletext",
	0xD0: "Printer Server Reply",
	0xD1: "Printer Server data",
	0xD2: "TCP/IP Protocol Suite - IP over Econet",
	0xD3: "SID Frame Slave, Fast FS_Control",
	0xD4: "Scrollarama",
	0xD5: "Phone",
	0xD6: "Broadcast Control",
	0xD7: "Broadcas tData",
	0xD8: "Impression Licence Checker",
	0xD9: "Digital Services Squirrel",
	0xDA: "SID Secondary, FastFS_Data",
	0xDB: "Digital Services Squirrel2",
	0xDC: "data Distribution Control, Cambridge Systems Design",
	0xDD: "data Distribution data, Cambridge Systems Design",
	0xDE: "Class ROM, Oak Solutions",
	0xDF: "Printer Spooler Command, Oak Solutions",
	0xE0: "Digital Services NetGain1, David Faulkner, Digital Services",
	0xE1: "Digital Services NetGain2, David Faulkner, Digital Services",
	0xE2: "AppFS1, Les Want, AppFS",
	0xE3: "AppFS2, Les Want, AppFS",
	0xE4: "Atom Wide Fax Net, Martin Coulson / Chris Ross",
	0xE5: "Atom Wide Print Net, Martin Coulson / Chris Ross",
	0xE6: "Iota data Power, Neil Raine, Iota",
	0xE7: "CD Net Server Broadcast, Ellis Hall, PEP Associates",
	0xE8: "CD Net Server Replies, Ellis Hall, PEP Associates",
	0xE9: "Class FS_Server, Oak Solutions",
	0xEA: "Digital Services Tape Store2, New allocation to replace 0x54",
	0xEB: "Developer Support, Mark/Jon communication port",
	0xEC: "LLS_Net, Longman Logotron S-Net server",
}
